Repository eslint/eslint-github-bot, pull requests merged in 2018-12, with the labels that each got.

#97 Upgrade: Various dependencies and fix unit test
  .eslintrc.js
  package-lock.json
  package.json
  src/plugins/check-unit-test/index.js
  src/plugins/duplicate-comments/index.js
  src/plugins/pr-ready-to-merge/reviewCheck.js
  src/plugins/release-monitor/index.js
  tests/__mocks__/probot-scheduler.js
  tests/plugins/issue-archiver/index.js
  tests/plugins/triage/index.js
Labels: chore

#96 New: auto-closer plugin (fixes #92)
  src/app.js
  src/plugins/auto-closer/index.js
  src/plugins/index.js
  tests/plugins/auto-closer/index.js
Labels: feature, plugin

#100 Fix: Autocloser bot plugin error (refs #98)
  README.md
  src/plugins/auto-closer/index.js
  tests/plugins/auto-closer/index.js
Labels: accepted, bug

#101 Fix: Auto-closer should not be closing pull requests (refs #98)
  src/plugins/auto-closer/index.js
  tests/plugins/auto-closer/index.js
Labels: accepted, bug
