Repository eslint/eslint-github-bot, pull requests merged in 2018-09, with the labels that each got.

#82 Fix: WIP plugin will create status check on synchronize (fixes #80)
  src/plugins/wip/index.js
  tests/plugins/wip/index.js
Labels: accepted, bug

#83 Upgrade: probot to v7.1.2
  package-lock.json
  package.json
  src/app.js
  src/plugins/recurring-issues/index.js
  tests/plugins/check-unit-test/index.js
  tests/plugins/commit-message/index.js
  tests/plugins/duplicate-comments/index.js
  tests/plugins/issue-archiver/index.js
  tests/plugins/needs-info/index.js
  tests/plugins/recurring-issues/index.js
  tests/plugins/release-monitor/index.js
  tests/plugins/triage/index.js
  tests/plugins/wip/index.js
Labels: triage

#85 Docs: add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#86 Fix: avoid reporting spurious for multiline commits referencing issues
  src/plugins/commit-message/index.js
  tests/plugins/commit-message/index.js
Labels: accepted, bug

#87 Chore: Travis builds on all branches
  .travis.yml
Labels: accepted, chore
