Repository eslint/eslint-github-bot, pull requests merged in 2018-08, with the labels that each got.

#79 Chore: fix broken test suite (fixes #76)
  package.json
  tests/plugins/issue-archiver/index.js
Labels: triage

#78 Chore: add package-lock.json
  .npmrc
  package-lock.json
Labels: triage

#74 Update: commit tag allowed `Revert`
  src/plugins/commit-message/index.js
  tests/plugins/commit-message/index.js
Labels: accepted, enhancement

#71 Docs: Add info about WIP tracker to README
  README.md
Labels: accepted, documentation

#70 Update: commit-message enforces issue ref style (fixes #56)
  src/plugins/commit-message/index.js
  tests/plugins/commit-message/index.js
Labels: accepted, enhancement, plugin

#81 Chore: update CI to match production environment
  .travis.yml
Labels: chore
