Repository eslint/eslint-github-bot, pull requests merged in 2024-03, with the labels that each got.

#202 fix: update Jenkins URL in release issue body
  src/plugins/recurring-issues/index.js
Labels: documentation

#203 fix: move `@eslint/js` release after other packages
  src/plugins/recurring-issues/index.js
Labels: bug

#206 build: Pin to Node.js 16.x
  package.json
Labels: build

#201 refactor: use flat config for eslint
  .eslintignore
  .eslintrc.js
  eslint.config.js
  package-lock.json
  package.json
  src/plugins/check-unit-test/index.js
  src/plugins/commit-message/index.js
  src/plugins/duplicate-comments/index.js
  src/plugins/pr-ready-to-merge/common.js
  src/plugins/pr-ready-to-merge/reviewCheck.js
  src/plugins/release-monitor/index.js
  src/plugins/wip/index.js
  tests/plugins/auto-closer/index.js
  tests/plugins/release-monitor/index.js
Labels: chore
